version: '3'

services:
  metadata:
    build:
      context: ./metadata
      dockerfile: ./metadata.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    ports:
      - "80:3000"
    volumes:
      - ./metadata/genesis-metadata/:/genesis-metadata/
      - ./metadata/starter-metadata/:/starter-metadata/

  deal:
    build:
      context: ./deal
      dockerfile: ./deal.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env

  rating:
    build:
      context: ./rating
      dockerfile: ./rating.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
