version: '3'

services:
  metadata:
    build:
      context: ./metadata
      dockerfile: ./metadata.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    ports:
      - "80:3000"

  caddy:
    image: takez0o/honestwork-caddy:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .caddy_data:/data
      - .caddy_config:/config

volumes:
  .caddy_data:
    external: true
  .caddy_config:
