version: '3'

services:
  metadata:
    image: takez0o/honestwork-metadata:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./metadata/genesis-metadata/:/genesis-metadata/

  deal:
    image: takez0o/honestwork-deal:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env

  rating:
    image: takez0o/honestwork-rating:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env

  caddy:
    image: takez0o/honestwork-caddy:0.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .caddy_data:/data
      - .caddy_config:/config

volumes:
  .caddy_data:
    external: true
  .caddy_config:
